# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [6]:
# Import NumPy as its abbreviation 'np'
import numpy as np
a =np.ones((2,3), dtype="int32")
a

array([[1, 1, 1],
       [1, 1, 1]])

In [7]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1,2,3,4,5,6,7,8,])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,2,3],
                 [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1,2,3],
                  [4,5,6]],
                 
                   [[7,8,9],
                 [10,11,12]]])


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [8]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape, arr1.ndim, arr1.dtype, arr1.size, type(arr1)

((8,), 1, dtype('int32'), 8, numpy.ndarray)

In [9]:
# Attributes of 2-dimensional array
arr2.shape, arr2.ndim, arr2.dtype, arr2.size, type(arr2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [10]:
# Attributes of 3-dimensional array
arr3.shape, arr3.ndim, arr3.dtype, arr3.size, type(arr3)

((2, 2, 3), 3, dtype('int32'), 12, numpy.ndarray)

In [14]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(arr2)
df

0  1  2
0  1  2  3
1  4  5  6

In [16]:
# Create an array of shape (10, 2) with only ones
np.ones((10,2)).astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [18]:
# Create an array of shape (7, 2, 3) of only zeros
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
# Create an array within a range of 0 and 100 with step 3
arr4 = np.arange(0,100,3)
arr4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [29]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr5 = np.random.randint(0,10,(7,2))
arr5

array([[9, 9],
       [8, 0],
       [5, 3],
       [0, 9],
       [1, 1],
       [6, 2],
       [3, 2]])

In [34]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr6 = np.random.random((3,5))
arr6

array([[0.30643624, 0.45752443, 0.09902819, 0.5840805 , 0.39959463],
       [0.84418872, 0.69903363, 0.54193666, 0.35988729, 0.47266216],
       [0.20816249, 0.81792011, 0.1083808 , 0.87528904, 0.04378169]])

In [37]:
# Set the random seed to 42

np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0,10,(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [41]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

arr7 = np.random.randint(1,10,(3,7))
# Find the unique numbers in the array you just created
np.unique(arr7)

array([1, 2, 3, 4, 5, 7, 9])

In [46]:
# Find the 0'th index of the latest array you created
arr7[0]
arr7

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [47]:
# Get the first 2 rows of latest array you created
arr7[:2,:]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [48]:
# Get the first 2 values of the first 2 rows of the latest array
arr7[:2,:2]

array([[9, 1],
       [5, 3]])

In [51]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr8 = np.random.randint(1,10,(3,5)) 
ones = np.ones((3,5))


array([[ 9.,  2.,  9.,  9.,  4.],
       [ 2.,  9.,  4.,  4.,  2.],
       [ 6.,  8., 10.,  8., 10.]])

In [52]:
# Add the two arrays together
arr8+ones

array([[10.,  3., 10., 10.,  5.],
       [ 3., 10.,  5.,  5.,  3.],
       [ 7.,  9., 11.,  9., 11.]])

In [53]:
# Create another array of ones of shape (5, 3)
ones1 = np.ones((5,3))

In [54]:
# Try add the array of ones and the other most recent array together
arr8+ones1

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [58]:
# Create another array of ones of shape (3, 5)
ones2 = np.ones((3,5))
ones2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
# Subtract the new array of ones from the other most recent array
arr8-ones2

array([[8., 1., 8., 8., 3.],
       [1., 8., 3., 3., 1.],
       [5., 7., 9., 7., 9.]])

In [59]:
# Multiply the ones array with the latest array
arr8*ones2

array([[ 9.,  2.,  9.,  9.,  4.],
       [ 2.,  9.,  4.,  4.,  2.],
       [ 6.,  8., 10.,  8., 10.]])

In [60]:
# Take the latest array to the power of 2 using '**'
arr8**2

array([[ 81.,   4.,  81.,  81.,  16.],
       [  4.,  81.,  16.,  16.,   4.],
       [ 36.,  64., 100.,  64., 100.]])

In [61]:
# Do the same thing with np.square()
np.square(arr8)

array([[ 81.,   4.,  81.,  81.,  16.],
       [  4.,  81.,  16.,  16.,   4.],
       [ 36.,  64., 100.,  64., 100.]])

In [62]:
# Find the mean of the latest array using np.mean()
np.mean(arr8)

6.4

In [63]:
# Find the maximum of the latest array using np.max()
np.max(arr8)

10.0

In [64]:
# Find the minimum of the latest array using np.min()
np.min(arr8)

2.0

In [65]:
# Find the standard deviation of the latest array
np.std(arr8)

2.9844039047465856

In [66]:
# Find the variance of the latest array
np.var(arr8)

8.906666666666666

In [69]:
# Reshape the latest array to (3, 5, 1)
arr8.reshape((3,5,1))

array([[[ 9.],
        [ 2.],
        [ 9.],
        [ 9.],
        [ 4.]],

       [[ 2.],
        [ 9.],
        [ 4.],
        [ 4.],
        [ 2.]],

       [[ 6.],
        [ 8.],
        [10.],
        [ 8.],
        [10.]]])

In [70]:
# Transpose the latest array
arr8.T

array([[ 9.,  2.,  6.],
       [ 2.,  9.,  8.],
       [ 9.,  4., 10.],
       [ 9.,  4.,  8.],
       [ 4.,  2., 10.]])

What does the transpose do?

In [71]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ar1 = np.random.randint(0,10, size=(3,3))
ar2 = np.random.randint(0,10,size=(3,2))

In [74]:
# Perform a dot product on the two newest arrays you created
ar3 = ar1.dot(ar2)
ar3

array([[35, 16],
       [58, 38],
       [48, 26]])

In [76]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ar4 = np.random.randint(0,10,size=(4,3))
ar5 = np.random.randint(0,10,size=(4,3))

In [77]:
# Perform a dot product on the two newest arrays you created
np.dot(ar4,ar5)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [81]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
ar4.T.shape
np.dot(ar4.T,ar5)

array([[108, 111,  69],
       [ 66,  79,  69],
       [106,  94, 116]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [83]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ar6 = np.random.randint(0,10,size=(3,4))
ar7 = np.random.randint(0,10,size=(3,4))

In [84]:
# Compare the two arrays with '>'
ar6>ar7

array([[ True, False,  True, False],
       [False,  True, False, False],
       [False,  True, False,  True]])

What happens when you compare the arrays with `>`?

In [85]:
# Compare the two arrays with '>='
ar6>=ar7

array([[ True, False,  True, False],
       [ True,  True,  True, False],
       [False,  True, False,  True]])

In [41]:
# Find which elements of the first array are greater than 7
ar6>ar7

In [86]:
# Which parts of each array are equal? (try using '==')
ar6==ar7

array([[False, False, False, False],
       [ True, False,  True, False],
       [False, False, False, False]])

In [87]:
# Sort one of the arrays you just created in ascending order
np.sort(ar6)

array([[3, 5, 6, 9],
       [0, 0, 6, 8],
       [3, 8, 8, 8]])

In [88]:
# Sort the indexes of one of the arrays you just created
np.argsort(ar6)

array([[1, 0, 3, 2],
       [2, 3, 1, 0],
       [2, 0, 1, 3]], dtype=int64)

In [89]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ar6)

2

In [90]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ar6)

6

In [91]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ar6, axis=1)

array([2, 0, 0], dtype=int64)

In [92]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ar6, axis=0)

array([0, 0, 1, 1], dtype=int64)

In [94]:
# Create an array of normally distributed random numbers
np.random.normal(2,3,(3,2))

array([[ 6.21187622,  1.94434759],
       [-3.02051387, -1.2175955 ],
       [-0.97775854,  2.30704305]])

In [95]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.